sudo: false
cache: bundler
language: ruby
bundler_args: --without development --quiet
before_script:
  - bundle exec rake test_app
script:
  - bundle exec rake
rvm:
  - 2.2.2
notifications:
  email:
    - seb@madetech.co.uk
branches:
  only:
    - master
