sudo: false
cache: bundler
language: ruby
bundler_args: --without development production --quiet
script:
  - bundle exec rake
rvm:
  - 2.2.2
notifications:
  email:
    - seb@madetech.co.uk
branches:
  only:
    - master
